name: openedge-actions
description: Setup OpenEdge and optionally run openedge source or ABLUnit tests
author: kenherring
branding:
  icon: loader
  color: blue

runs:
  using: composite
  steps:

    - uses: jenseng/dynamic-uses@v1.1.1
      env:
        action_ref: ${{ github.action_ref }}
      with:
        uses: kenherring/openedge-actions/setup@${{ github.repository == 'kenherring/openedge-actions' && github.sha || env.action_ref }}

    ## need to use dynamic uses above because actions local to the first action called don't work
    # - id: setup-abl
    #   name: setup-abl
    #   uses: ./setup
