name: kenherring/openedge-actions/ablunit
description: Execute OpenEdge ABLUnit Tests
author: kenherring

inputs:
  ## ----- setup ----- ##
  license:
    description: Path to a license file or a secret value which is the base64 encoded license with newlines replaced with spaces
    required: false
  version:
    description: The ABL version to use
    required: false
    default: latest
  dlc:
    description: Target path for ABL installation, defaults to /psc/dlc-${version}
    required: false
  cache-key:
    description: An explicit key for a cache entry, or 'null' to disable caching
    required: false
  cache-token:
    description: Value added to cache key, used to forcefully expire the cache if needed
    required: false
  ## ----- run ----- ##
  working-directory:
    description: The working directory to run the tests in
    required: false
  propath:
    description: Initial propath, set via PROPATH environment variable
    required: false
    default: .
  batch-mode:
    description: Startup parameter -b
    required: false
    default: 'true'
  startup-procedure:
    description: Startup parameter -p
    required: false
    default: ABLUnitCore.p
  parameter-file:
    description: Startup parameter -pf
    required: false
  temp-directory:
    description: Startup parameter -T
    required: false
    default: /tmp
  parameter:
    description: Startup parameter -param
    required: false
  additional-parameters:
    description: Additional startup parameters
    required: false
  ## ----- ablunit ----- ##
  test-file-pattern:
    description: Pattern to match ABLUnit test files
    required: false
    default: '*.cls,**/*.cls,*.p,**/*.p'
  ablunit-json:
    description: The ABLUnit configuration file, will be generated when not provided
    required: false
    default: ablunit.json
  debug:
    description: Additional debug logging
    required: false
    default: "true"

outputs:
  test-count:
    description: total tests found
    value: ${{ steps.analyze-results.outputs.test-count }}
  failure-count:
    description: tests failed
    value: ${{ steps.analyze-results.outputs.failure-count }}
  error-count:
    description: tests with errors
    value: ${{ steps.analyze-results.outputs.error-count }}
  skipped-count:
    description: tests skipped
    value: ${{ steps.analyze-results.outputs.skipped-count }}

runs:
  using: composite
  steps:

    - id: ablunit-init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ABLUNIT_JSON: ${{ inputs.ablunit-json }}
        PROPATH: ${{ inputs.propath }}
        TEST_FILE_PATTERN: ${{ inputs.test-file-pattern }}
      run: ${{ github.action_path }}/ablunit_init.sh

    - uses: jenseng/dynamic-uses@v1.1.1
      env:
        action_ref: ${{ github.action_ref }}
      with:
        uses: kenherring/openedge-actions/run@${{ github.repository == 'kenherring/openedge-actions' && github.sha || env.action_ref }}
        with: |
          { "license": ${{ inputs.license }},
            "version": ${{ inputs.version }},
            "dlc": ${{ inputs.dlc }},
            "cache-key": ${{ inputs.cache-key }},
            "cache-token": ${{ inputs.cache-token }},
            "working-directory": ${{ inputs.working-directory }},
            "propath": "${{ inputs.propath }},$DLC/src/ablunit",
            "startup-procedure": ${{ inputs.startup-procedure }},
            "parameter-file": ${{ inputs.parameter-file }},
            "temp-directory": ${{ inputs.temp-directory }},
            "parameter": CFG=${{ steps.ablunit-init.outputs.ablunit-json }},
            "additional-parameters": ${{ inputs.additional-parameters }}
          }

    - id: analyze-results
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ABLUNIT_JSON: ${{ steps.ablunit-init.outputs.ablunit-json }}
        ACTIONS_STEP_DEBUG: ${{ inputs.debug }}
        DELETE_ABLUNIT_JSON: ${{ steps.ablunit-init.outputs.created-ablunit-json }}
      run: ${{ github.action_path }}/analyze_results.sh
