class src.someClass :

    /*------------------------------------------------------------------------------
        Purpose: A sample method with documentation
        Notes: These are notes!
        @param parameter1 an integer parameter
        @return
    ------------------------------------------------------------------------------*/
    method public void some_method (parameter1 as integer) :
        message "ran some_procedure with parameter1=" + string(parameter1).
    end method.

end class.
