name: openedge-actions/run
description: Execute an OpenEdge source program
author: kenherring

inputs:
  ##### actions-setup-abl #####
  license:
    description: Path to a license file or a secret value which is the base64 encoded license with newlines replaced with spaces
    required: false
  version:
    description: The ABL version to use
    required: false
    default: latest
  dlc:
    description: Target path for ABL installation, defaults to /psc/dlc-${version}
    required: false
  download-ade-source:
    description: Download progress/ADE and add it to the propath when 'true' (all other values evaluates to false)
    required: false
    default: 'false'
  cache-key:
    description: An explicit key for a cache entry, or 'null' to disable caching
    required: false
  cache-token:
    description: Value added to cache key, used to forcefully expire the cache if needed
    required: false
  ##### environment #####
  propath:
    description: Initial propath, set via PROPATH environment variable
    required: false
    default: .
  ##### startup parameters #####
  batch-mode:
    description: Startup parameter -b
    required: false
    default: 'true'
  startup-procedure:
    description: Startup parameter -p
    required: true
  temp-directory:
    description: Startup parameter -T
    required: false
    default: /tmp
  parameter:
    description: Startup parameter -param
    required: false

runs:
  using: composite
  steps:

    - name: set-github-path
      shell: bash
      env:
        ACTION_REPOSITORY: ${{ github.action_repository }}
        ACTION_REF: ${{ github.action_ref }}
        REPOSITORY: ${{ github.repository }}
      run: |
        env | sort

        echo '${{ github.action_path }}' >> $GITHUB_PATH

        echo "ACTION_REPOSITORY=$ACTION_REPOSITORY"
        echo "ACTION_REF=$ACTION_REF"
        echo "REPOSITORY=$REPOSITORY"
        if [ "$ACTION_REPOSITORY" = "$REPOSITORY" ]; then
          echo "MATCH!"
          echo "action-ref=${{ github.ref }}"
          echo "action-ref=${{ github.ref }}" >> $GITHUB_OUTPUTS
        fi

        # echo "github.action_path=${{ github.action_path }}"
        # ls -al "${{ github.action_path }}"
        # DIR_1="$(dirname "${{github.action_path}}")"
        # echo "DIR_1=$DIR_1"
        # cd "$DIR_1"
        # ls -al

        # ## only when called from another repo
        # echo "github.ref=${{ github.ref }}"
        # echo "github.repo=${{ github.repo }}"

        # if [ "${{ github.repo }}" == "kenherring/openedge-actions" ]; then
        #   echo "action-ref=${{ github.ref }}"
        #   echo "action-ref=${{ github.ref }}" >> $GITHUB_OUTPUTS
        # else
        #   echo "action-ref=$(basename "$DIR_1")
        #   echo "action-ref=$(basename "$DIR_1")" >> $GITHUB_OUTPUTS
        # fi



    - uses: jenseng/dynamic-uses@v1
      with:
        # now you can use expressions 🥳
        uses: kenherring/openedge-actions/setup@${{ steps.set-github-path.outputs.action-ref }}
        # the `with` needs to be converted to a valid json string
        with: |
          {  "license": ${{ inputs.license }},
              "version": ${{ inputs.version }},
              "dlc": ${{ inputs.dlc }},
              "download-ade-source": ${{ inputs.download-ade-source }},
              "cache-key": ${{ inputs.cache-key }},
              "cache-token": ${{ inputs.cache-token }}
          }

    # - uses: ./setup
    #   # uses: kenherring/openedge-actions/setup@${{ github.ref }}
    #   with:
    #     license: ${{ inputs.license }}
    #     version: ${{ inputs.version }}
    #     dlc: ${{ inputs.dlc }}
    #     download-ade-source: ${{ inputs.download-ade-source }}
    #     cache-key: ${{ inputs.cache-key }}
    #     cache-token: ${{ inputs.cache-token }}

    - id: run-abl
      name: run-abl
      shell: bash
      env:
        OPT_PROPATH: ${{ inputs.propath }}
        OPT_BATCH_MODE: ${{ inputs.batch-mode }}
        OPT_PARAMETER: ${{ inputs.parameter }}
        OPT_STARTUP_PROCEDURE: ${{ inputs.startup-procedure }}
        OPT_TEMP_DIRECTORY: ${{ inputs.temp-directory }}
      run: abl_run.sh
