name: openedge-actions/documentation
description: Generate OpenEdge JsonDocumentation
author: kenherring

inputs:
  ##### actions-setup-abl #####
  license:
    description: Path to a license file or a secret value which is the base64 encoded license with newlines replaced with spaces
    required: false
  version:
    description: The ABL version to use
    required: false
    default: latest
  dlc:
    description: Target path for ABL installation, defaults to /psc/dlc-${version}
    required: false
  cache-key:
    description: An explicit key for a cache entry, or 'null' to disable caching
    required: false
  cache-token:
    description: Value added to cache key, used to forcefully expire the cache if needed
    required: false
  ##### environment #####
  working-directory:
    description: The working directory to run the OpenEdge program in
    required: false
  propath:
    description: Initial propath, set via PROPATH environment variable
    required: false
    default: .
  artifact-name:
    description: Artifact name for uploading documentation
    required: false
  ##### Compile Options #####
  skip-compile:
    description: Skip compilation
    required: false
    default: "false"
  ##### JsonDocumentation Options #####
  pct-destFile:
    description: JSON file output
    required: false
    default: 'documentation.json'
  pct-buildDir:
    description: Directory where rcode will be read
    required: false
  pct-encoding:
    description: Use specific encoding when reading source files
    required: false
  pct-style:
    description: "Comment style: Javadoc (/**), simple (/*), consultingwerk (/*-)"
    required: false
    default: "Javadoc"
  pct-indent:
    description: JSON pretty-printing
    required: false
    default: "false"

runs:
  using: composite
  steps:

    - name: set-github-path
      id: set-github-path
      shell: bash
      env:
        ACTION_REF: ${{ github.action_ref }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        echo '${{ github.action_path }}' >> "$GITHUB_PATH"
        echo "action-ref=${ACTION_REF:-$GITHUB_SHA}" >> "$GITHUB_OUTPUT"

    - uses: jenseng/dynamic-uses@v1.1.1
      if: ${{ inputs.license }}
      with:
        uses: kenherring/openedge-actions/setup@${{ steps.set-github-path.outputs.action-ref }}
        with: |
          {  "license": "${{ inputs.license }}",
              "version": ${{ inputs.version }},
              "dlc": ${{ inputs.dlc }},
              "download-ade-source": ${{ inputs.download-ade-source }},
              "cache-key": ${{ inputs.cache-key }},
              "cache-token": ${{ inputs.cache-token }}
          }

    - uses: jenseng/dynamic-uses@v1.1.1
      if: ${{ inputs.license && inputs.skip-compile != true }}
      with:
        uses: kenherring/openedge-actions/compile@${{ steps.set-github-path.outputs.action-ref }}
        with: |
          {  "license": "${{ inputs.license }}",
              "version": ${{ inputs.version }},
              "dlc": ${{ inputs.dlc }},
              "cache-key": ${{ inputs.cache-key }},
              "cache-token": ${{ inputs.cache-token }},
              "working-directory": ${{ inputs.working-directory }},
              "propath": ${{ inputs.propath }},
              "pct-destDir": ${{ inputs.pct-buildDir }}
          }

    - id: abl-json-documentation
      name: abl-json-documentation
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        PROPATH: ${{ inputs.propath }}
        PCT_destFile: ${{ inputs.pct-destFile }}
        PCT_buildDir: ${{ inputs.pct-buildDir }}
        PCT_encoding: ${{ inputs.pct-encoding }}
        PCT_style: ${{ inputs.pct-style }}
        PCT_indent: ${{ inputs.pct-indent }}
      run: generate_documentation.sh

    - uses: actions/upload-artifact@v4
      if: ${{ inputs.artifact-name && inputs.artifact-name != '' }}
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          ${{ inputs.working-directory }}/${{ inputs.pct-destFile }}
        if-no-files-found: error
